version: '3.8'
services:
  db:
    image: postgres:latest
    #    container_name: postgres-emociones
    restart: always
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=emociones
      - POSTGRES_USER=lgalindop
      - POSTGRES_PASSWORD=perro
      - POSRGRES_PORT=5432

    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local